Traceback (most recent call last):
  File "middleman.py", line 13, in <module>
    server_facing_socket.connect((ip, int(server_port)))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
